package com.example.roomdatabasedemo

import androidx.room.Entity
import androidx.room.PrimaryKey

// Defines the 'Note' data class, which represents a table in the Room database.
// The tableName is explicitly set to "notes".
@Entity(tableName = "notes")
data class Note(
    // Primary key for the 'notes' table, automatically generated by the database.
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    // The title of the note.
    val title: String,
    // The main content/body of the note.
    val content: String,
    // The date when the note was created or last updated.
    val date: String
)